trigger:
  branches:
    include:
      - main  # Runs on main branch push

pool:
  name: 'azureagent'  # Use self-hosted agent

stages:
- stage: Build
  jobs:
  - job: Build_Job
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        architecture: 'x64'

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install Dependencies'

    - script: |
        pytest tests/
      displayName: 'Run Tests'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)'
        artifactName: 'drop'
